apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  template:
    spec:
      containers:
      - name: init
        args: [pulsar, init, -t, "persistent://public/default/at-least-once-test-abc"]
        env:
        - name: PULSAR_CLIENT_authPluginClassName
          value: org.apache.pulsar.client.impl.auth.AuthenticationToken
