apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  template:
    spec:
      containers:
      - name: producer
        args: [pulsar, at-least-once, produce, -m, "100000", -r, "100"]
        env:
        - name: PULSAR_CLIENT_authPluginClassName
          value: org.apache.pulsar.client.impl.auth.AuthenticationToken
        - name: PULSAR_CLIENT_authParams
          value: file:///mnt/secret/token
        - name: PULSAR_CONSUMER_topicNames
          value: persistent://public/default/at-least-once-test-abc
        - name: PULSAR_CONSUMER_subscriptionName
          value: sub-1
        - name: PULSAR_CONSUMER_subscriptionType
          value: Shared
