apiVersion: batch/v1
kind: Job
metadata:
  name: producer
spec:
  template:
    spec:
      containers:
      - name: producer
        args: [pulsar, at-least-once, produce, -m, "100000", -r, "100"]
        env:
        - name: PULSAR_CLIENT_authPluginClassName
          value: org.apache.pulsar.client.impl.auth.AuthenticationToken
        - name: PULSAR_PRODUCER_topicName
          value: persistent://public/default/at-least-once-test-abc
