apiVersion: batch/v1
kind: Job
metadata:
  name: init
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image: streamnative/chaos-test:master
        imagePullPolicy: Always
        command: [/chaos/runner/bin/runner]
        env:
        - name: PULSAR_CLIENT_authParams
          value: file:///mnt/secret/token
        volumeMounts:
        - mountPath: /mnt/secret
          name: client-token
          readOnly: true
      volumes:
      - name: client-token
        secret:
          defaultMode: 420
          items:
          - key: TOKEN
            path: token
          secretName: proxy-auth-token-admin
