apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-abc
      component: ut-worker
  template:
    metadata:
      labels:
        app: producer-abc
        component: ut-worker
    spec:
      containers:
      - name: producer
        image: streamnative/chaos-test:master
        imagePullPolicy: Always
        command: [/chaos/runner/bin/runner]
        args: [pulsar, at-least-once, produce, -m, "100000", -r, "100"]
        env:
        - name: PULSAR_CLIENT_serviceUrl
          value: pulsar://proxy-auth-snp-proxy-headless.ut-proxy-auth.svc.cluster.local:6650
        - name: PULSAR_CLIENT_authPluginClassName
          value: org.apache.pulsar.client.impl.auth.AuthenticationToken
        - name: PULSAR_CLIENT_authParams
          value: file:///mnt/secret/token
        - name: PULSAR_CONSUMER_topicNames
          value: persistent://public/default/at-least-once-test-abc
        - name: PULSAR_CONSUMER_subscriptionName
          value: sub-1
        - name: PULSAR_CONSUMER_subscriptionType
          value: Shared
        volumeMounts:
        - name: persistent-storage
          mountPath: /tmp/msit
        - mountPath: /mnt/secret
          name: client-token
          readOnly: true
      volumes:
      - name: client-token
        secret:
          defaultMode: 420
          items:
          - key: TOKEN
            path: token
          secretName: proxy-auth-token-admin
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pc-share
