apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pc-share
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: sn-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
